//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekti_KNK.Gjuha {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class anglisht {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal anglisht() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projekti_KNK.Gjuha.anglisht", typeof(anglisht).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic of records.
        /// </summary>
        internal static string btn_Grafika {
            get {
                return ResourceManager.GetString("btn_Grafika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btn_Pastro {
            get {
                return ResourceManager.GetString("btn_Pastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btn_Ruaj {
            get {
                return ResourceManager.GetString("btn_Ruaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcript of records.
        /// </summary>
        internal static string btn_transkripti {
            get {
                return ResourceManager.GetString("btn_transkripti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnAnloD {
            get {
                return ResourceManager.GetString("btnAnloD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnAnloP {
            get {
                return ResourceManager.GetString("btnAnloP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnAnulo {
            get {
                return ResourceManager.GetString("btnAnulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnAnuloA {
            get {
                return ResourceManager.GetString("btnAnuloA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnAnuloL {
            get {
                return ResourceManager.GetString("btnAnuloL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnAnuloP1 {
            get {
                return ResourceManager.GetString("btnAnuloP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnAnuloS {
            get {
                return ResourceManager.GetString("btnAnuloS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Exams.
        /// </summary>
        internal static string btnParaqit {
            get {
                return ResourceManager.GetString("btnParaqit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnRuaje {
            get {
                return ResourceManager.GetString("btnRuaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnRuajeA {
            get {
                return ResourceManager.GetString("btnRuajeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnRuajeD {
            get {
                return ResourceManager.GetString("btnRuajeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnRuajeL {
            get {
                return ResourceManager.GetString("btnRuajeL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnRuajeP {
            get {
                return ResourceManager.GetString("btnRuajeP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnRuajeP1 {
            get {
                return ResourceManager.GetString("btnRuajeP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnRuajeS {
            get {
                return ResourceManager.GetString("btnRuajeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string Forma_Admin {
            get {
                return ResourceManager.GetString("Forma_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form_Professor.
        /// </summary>
        internal static string Forma_Profesorit {
            get {
                return ResourceManager.GetString("Forma_Profesorit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Forma_Student {
            get {
                return ResourceManager.GetString("Forma_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Administrators.
        /// </summary>
        internal static string frm_SHA {
            get {
                return ResourceManager.GetString("frm_SHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        internal static string grb_GJA {
            get {
                return ResourceManager.GetString("grb_GJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        internal static string grb_GJP {
            get {
                return ResourceManager.GetString("grb_GJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify.
        /// </summary>
        internal static string Identifikohu {
            get {
                return ResourceManager.GetString("Identifikohu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday:.
        /// </summary>
        internal static string lbl_DA {
            get {
                return ResourceManager.GetString("lbl_DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate:.
        /// </summary>
        internal static string lbl_Ditlindja1 {
            get {
                return ResourceManager.GetString("lbl_Ditlindja1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate:.
        /// </summary>
        internal static string lbl_DP {
            get {
                return ResourceManager.GetString("lbl_DP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        internal static string lbl_Drejtimi {
            get {
                return ResourceManager.GetString("lbl_Drejtimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string lbl_DrejtimiP {
            get {
                return ResourceManager.GetString("lbl_DrejtimiP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Registration.
        /// </summary>
        internal static string lbl_DRP {
            get {
                return ResourceManager.GetString("lbl_DRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string lbl_EA {
            get {
                return ResourceManager.GetString("lbl_EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string lbl_Email1 {
            get {
                return ResourceManager.GetString("lbl_Email1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string lbl_EmailA {
            get {
                return ResourceManager.GetString("lbl_EmailA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string lbl_EmailP {
            get {
                return ResourceManager.GetString("lbl_EmailP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string lbl_EP {
            get {
                return ResourceManager.GetString("lbl_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade:.
        /// </summary>
        internal static string lbl_GA {
            get {
                return ResourceManager.GetString("lbl_GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        internal static string lbl_ID {
            get {
                return ResourceManager.GetString("lbl_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname:.
        /// </summary>
        internal static string lbl_MA {
            get {
                return ResourceManager.GetString("lbl_MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname:.
        /// </summary>
        internal static string lbl_MP {
            get {
                return ResourceManager.GetString("lbl_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average grade .
        /// </summary>
        internal static string lbl_NM {
            get {
                return ResourceManager.GetString("lbl_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string lbl_PA {
            get {
                return ResourceManager.GetString("lbl_PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string lbl_Pastro {
            get {
                return ResourceManager.GetString("lbl_Pastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string lbl_PP {
            get {
                return ResourceManager.GetString("lbl_PP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor:.
        /// </summary>
        internal static string lbl_Profesori {
            get {
                return ResourceManager.GetString("lbl_Profesori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of Department.
        /// </summary>
        internal static string lbl_ShD {
            get {
                return ResourceManager.GetString("lbl_ShD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile:.
        /// </summary>
        internal static string lbl_TA {
            get {
                return ResourceManager.GetString("lbl_TA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        internal static string lbl_Teli {
            get {
                return ResourceManager.GetString("lbl_Teli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        internal static string lbl_TP {
            get {
                return ResourceManager.GetString("lbl_TP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthplace:.
        /// </summary>
        internal static string lbl_VA {
            get {
                return ResourceManager.GetString("lbl_VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthplace:.
        /// </summary>
        internal static string lbl_Vendlindja1 {
            get {
                return ResourceManager.GetString("lbl_Vendlindja1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthplace:.
        /// </summary>
        internal static string lbl_VP {
            get {
                return ResourceManager.GetString("lbl_VP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Lastname:.
        /// </summary>
        internal static string lblEmri {
            get {
                return ResourceManager.GetString("lblEmri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECTS:.
        /// </summary>
        internal static string lblETCs {
            get {
                return ResourceManager.GetString("lblETCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class:.
        /// </summary>
        internal static string lblLenda {
            get {
                return ResourceManager.GetString("lblLenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string lblLloji {
            get {
                return ResourceManager.GetString("lblLloji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours:.
        /// </summary>
        internal static string lblOre {
            get {
                return ResourceManager.GetString("lblOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string lblPasswoed {
            get {
                return ResourceManager.GetString("lblPasswoed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester:.
        /// </summary>
        internal static string lblSemestri {
            get {
                return ResourceManager.GetString("lblSemestri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string lblShkyqu {
            get {
                return ResourceManager.GetString("lblShkyqu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string rbt_FA {
            get {
                return ResourceManager.GetString("rbt_FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string rbt_FP {
            get {
                return ResourceManager.GetString("rbt_FP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string rbt_MA {
            get {
                return ResourceManager.GetString("rbt_MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string rbt_MP {
            get {
                return ResourceManager.GetString("rbt_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string rdbAnglisht {
            get {
                return ResourceManager.GetString("rdbAnglisht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shqip.
        /// </summary>
        internal static string rdbSHQIP {
            get {
                return ResourceManager.GetString("rdbSHQIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New department.
        /// </summary>
        internal static string Sh_Drejtimet {
            get {
                return ResourceManager.GetString("Sh_Drejtimet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Classes.
        /// </summary>
        internal static string Sh_Lendet {
            get {
                return ResourceManager.GetString("Sh_Lendet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Professor&apos;s Class.
        /// </summary>
        internal static string Sh_Percakto_Prof_Lenden {
            get {
                return ResourceManager.GetString("Sh_Percakto_Prof_Lenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Professor.
        /// </summary>
        internal static string Sh_Profesor {
            get {
                return ResourceManager.GetString("Sh_Profesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Student.
        /// </summary>
        internal static string Sh_Student {
            get {
                return ResourceManager.GetString("Sh_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;List.
        /// </summary>
        internal static string tsm_Lista {
            get {
                return ResourceManager.GetString("tsm_Lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string tsm_Lista_A {
            get {
                return ResourceManager.GetString("tsm_Lista_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string tsm_Lista_D {
            get {
                return ResourceManager.GetString("tsm_Lista_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string tsm_Lista_L {
            get {
                return ResourceManager.GetString("tsm_Lista_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Classes.
        /// </summary>
        internal static string tsm_Lista_lL {
            get {
                return ResourceManager.GetString("tsm_Lista_lL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Professors.
        /// </summary>
        internal static string tsm_Lista_lP {
            get {
                return ResourceManager.GetString("tsm_Lista_lP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        internal static string tsm_Lista_P {
            get {
                return ResourceManager.GetString("tsm_Lista_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string tsm_Lista_S {
            get {
                return ResourceManager.GetString("tsm_Lista_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Professor.
        /// </summary>
        internal static string tsm_PercaktoProf {
            get {
                return ResourceManager.GetString("tsm_PercaktoProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        internal static string tsm_Regjistrimi {
            get {
                return ResourceManager.GetString("tsm_Regjistrimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string tsm_Regjistrimi_A {
            get {
                return ResourceManager.GetString("tsm_Regjistrimi_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string tsm_Regjistrimi_D {
            get {
                return ResourceManager.GetString("tsm_Regjistrimi_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string tsm_Regjistrimi_L {
            get {
                return ResourceManager.GetString("tsm_Regjistrimi_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Class.
        /// </summary>
        internal static string tsm_Regjistrimi_LeRE {
            get {
                return ResourceManager.GetString("tsm_Regjistrimi_LeRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        internal static string tsm_Regjistrimi_P {
            get {
                return ResourceManager.GetString("tsm_Regjistrimi_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string tsm_Regjistrimi_S {
            get {
                return ResourceManager.GetString("tsm_Regjistrimi_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string tss_Administrator {
            get {
                return ResourceManager.GetString("tss_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        internal static string tss_PA {
            get {
                return ResourceManager.GetString("tss_PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        internal static string tss_PS {
            get {
                return ResourceManager.GetString("tss_PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string tss_Student {
            get {
                return ResourceManager.GetString("tss_Student", resourceCulture);
            }
        }
    }
}
